### PR TITLE
Add running & auto run

### PR DESCRIPTION
**Pull request by Marioalexsan**
Should be similar to Deltarune: hold X to run, or when AutoRun is enabled hold X to walk at normal speed.

I added a new tab in decomp settings since we ran out of space in the General tab.

### CODE REVIEW

**Comment by Vultumast** [comment]
I feel like this is going to break alot of the game, because the game sorta depends on you not being able to run. I'll look into this and I'm going to look into making the the decomp settings scroll

**Comment by danielah05** [comment]
this causes game crashes (mainly in battles), not because of ur new code, but im pretty sure theres some weird bug with the latest studio 2 that fucks up the project file (NXTALE.yyp) whenever u add a new asset to the project (this has been an issue twice now on the experimental-tiles branch), i could be wrong tho. only thing u can really do about this is to grab an older version of the yyp and to manually readd the new files into it using something like notepad++ (or whatever text editor u prefer), this needs to be done before this can be even considered to be merged unfortunately

**Comment by Marioalexsan** [comment]
For now I've pushed a clean NXTALE.yyp that only adds the new script at the end of the resources list; but yeah, it's probably a good idea to wait on this PR until the .yyp issues get solved and we know the run function doesn't break the game.

**Comment by danielah05** [comment]
doing some testing rn and i already found ways to softlock the game with this (mainly with toriel in the ruins), i also somehow managed to skip the dummy tutorial with this. i feel like a decent amount of the game would need fixes for this feature in specific to work properly so u dont accidentally get stuck anywhere, either that or a warning needs to be added that specifies its a bit messy?

**Comment by Vultumast** [comment]
I think this is a cool feature, but it would break a majority of the game, so I'm going to close it for now

**Pull request closed without merging**
